# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Proficiency_Exercise' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Proficiency_Exercise

  target 'Proficiency_ExerciseTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SDWebImage', '~>4.0'

  end

end
